# Generated by Django 4.2.6 on 2024-03-06 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="userId",
        ),
    ]
