# Generated by Django 4.2.6 on 2024-03-06 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_profile_userid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
