# Generated by Django 4.2.6 on 2024-03-06 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
