# Generated by Django 4.2.6 on 2024-03-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporaryrating",
            name="movieId",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
