# Generated by Django 4.2.6 on 2024-03-08 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_temporaryrating_movieid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TemporaryRating",
        ),
    ]
